[project]
name = "25-openai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["dotenv>=0.9.9", "openai-agents>=0.6.4", "resend>=2.19.0"]

[dependency-groups]
dev = ["watchdog>=6.0.0"]
