[project]
name = "20-mcp-stytch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=2.14.1",
    "sqlalchemy>=2.0.45",
    "stytch>=14.0.0",
]
